### ISSUE TITLE
logical error in substring

### ISSUE THREAD

**Issue by nodegin** [s-yadav/FlakeId#6]
When bid is `"1100000010000101111100010101000010011111000000000000"`
It ends up the `id` became `null`
The `for` statement is `for (var i = bid.length; i >= 0; i -= 4)`
I think it should be `for (var i = bid.length; i > 0; i -= 4)`

**Comment by dustinrouillard** [comment]
This is an old issue. but because of neglect of the original code, I recreated it and have published it to npm.

[github.com/TheTetrabyte/snowflake-id](https://github.com/TheTetrabyte/snowflake-id)
[npmjs.com/package/snowflake-id](https://www.npmjs.com/package/snowflake-id)

Tired of it being broken, pftt. If the owner cares he should've maintained his code. Easy as that.

**Comment by s-yadav** [comment]
@TheTetrabyte I can understand your frustration. But along with having work which pays your bills, sometime you miss the github notifications (mails) or forgot to take action on the items. 
But I see there is a PR raised for this. I will merge it.

**Comment by s-yadav** [comment]
Release it on v0.4.0. @nodegin @TheTetrabyte Thanks for reporting.
